// Package golangci builds a project's .golangci.yml. golangci-lint has no way to extend
// another config, so forgego merges its base config with the project's own changes.
package golangci

import (
	"github.com/apollogeddon/forgego/internal/templates"
	"github.com/apollogeddon/forgego/internal/yamlx"
)

const (
	// BasePath is forgego's managed base config.
	BasePath = ".forgego/golangci.yml"
	// LocalPath holds the project's changes to the base config.
	LocalPath = ".golangci.local.yml"
	// ConfigPath is the merged config golangci-lint reads.
	ConfigPath = ".golangci.yml"
)

const header = `# Generated by forgego from .forgego/golangci.yml and .golangci.local.yml.
# Don't edit it: change .golangci.local.yml, then run ` + "`task sync`" + `.
`

// LocalStarter is the .golangci.local.yml a new project starts with.
const LocalStarter = `# This project's changes to forgego's golangci-lint config (.forgego/golangci.yml).
# Mappings merge key by key, lists gain the items listed here, and any other value
# replaces the base one. Run ` + "`task sync`" + ` after editing to regenerate .golangci.yml.
#
# linters:
#   enable:
#     - wsl_v5
#   settings:
#     gosec:
#       excludes:
#         - G104
version: "2"
`

// Base is forgego's base config.
func Base() string { return templates.Config("golangci.yml") }

// Render merges the project's local config into the base config.
func Render(local string) (string, error) {
	base, err := yamlx.Parse(Base())
	if err != nil {
		return "", err
	}
	// The base file's own header comment is about the base file, not the merged one.
	if len(base.Content) > 0 {
		base.Content[0].HeadComment = ""
	}
	overlay, err := yamlx.Parse(local)
	if err != nil {
		return "", err
	}
	out, err := yamlx.Encode(yamlx.Merge(base, overlay))
	if err != nil {
		return "", err
	}
	return header + out, nil
}
